import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import { PrismaClient } from '@prisma/client';  
import TabComponent from '../components/TabComponent';
import Header from '../components/Header'; 

   
const prisma = new PrismaClient();

export default function Home({tab}) {

  console.log(tab)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <TabComponent tab={tab}>

      </TabComponent>
      
      
    </div>
  )
}

export async function getServerSideProps() {
  const tab = await prisma.tab.findMany({
    select: {
      id: true,
      title: true,
      notes: true,
    },
  });    
  //const post = await prisma.post.findMany({where: {authorId: 1}}); 
  return {
    props: {
      
      tab: tab,  
      
    }
  }
}
