import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import { PrismaClient } from '@prisma/client';  
import TabComponent from '../components/TabComponent';
import Header from '../components/Header'; 

   
const prisma = new PrismaClient();

export default function Home({tab, note}) {

  console.log(tab)
  console.log(note)
  return (
    <div >
      <Head>
        <title>Tabbed Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <TabComponent tab={tab} note={note}> 

      </TabComponent>
      
      
    </div>
  )
}

export async function getServerSideProps() {
  const tab = await prisma.tab.findMany({
    select: {
      id: true,
      title: true,
      notes: true,
    },
  }); 
  const notes = await prisma.note.findMany({
    select: {
      id: true,
      tabId: true,
      body: true
    }
  })   
  //const post = await prisma.post.findMany({where: {authorId: 1}}); 
  return {
    props: {
      
      tab: tab,  
      note: notes
    }
  }
}
